services:
  db:
    image: postgres
    volumes:
      - ./backend/src/utils/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"


  backend:
    build:
      context: ./backend
    command: >
      sh -c "npm install && npx nest start --watch"
    volumes:
    - ./backend:/workspace/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/workspace/frontend
      - /workspace/frontend/node_modules
    ports:
      - "5173:5173"
